<?php
if ( ! defined( 'ABSPATH' ) ) exit;

function wysj_serv_iconbox($boxId,$inputName)//非自定义图标选择
{
?>
<div class="wy-iconbox" id="<?php echo $boxId; ?>">
	<ul>
		<li><a href="javascript:;" class="wysj wysj-whatsapp1" icon-class="wysj-whatsapp1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-whatsApp" icon-class="wysj-whatsApp"></a></li>
		<li><a href="javascript:;" class="wysj wysj-whatsapp" icon-class="wysj-whatsapp"></a></li>
		<li><a href="javascript:;" class="wysj wysj-huanyihuan" icon-class="wysj-huanyihuan"></a></li>
		<li><a href="javascript:;" class="wysj wysj-changyonggoupiaorenshanchu" icon-class="wysj-changyonggoupiaorenshanchu"></a></li>
		<li><a href="javascript:;" class="wysj wysj-yanchurili" icon-class="wysj-yanchurili"></a></li>
		<li><a href="javascript:;" class="wysj wysj-qiandao" icon-class="wysj-qiandao"></a></li>
		<li><a href="javascript:;" class="wysj wysj-xiaoxi" icon-class="wysj-xiaoxi"></a></li>
		<li><a href="javascript:;" class="wysj wysj-saoyisao1" icon-class="wysj-saoyisao1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-shoucang" icon-class="wysj-shoucang"></a></li>
		<li><a href="javascript:;" class="wysj wysj-zanting" icon-class="wysj-zanting"></a></li>
		<li><a href="javascript:;" class="wysj wysj-shenfenzheng" icon-class="wysj-shenfenzheng"></a></li>
		<li><a href="javascript:;" class="wysj wysj-bofang" icon-class="wysj-bofang"></a></li>
		<li><a href="javascript:;" class="wysj wysj-saoyisao" icon-class="wysj-saoyisao"></a></li>
		<li><a href="javascript:;" class="wysj wysj-qqqun1" icon-class="wysj-qqqun1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-tieba" icon-class="wysj-tieba"></a></li>
		<li><a href="javascript:;" class="wysj wysj-tianmao3" icon-class="wysj-tianmao3"></a></li>
		<li><a href="javascript:;" class="wysj wysj-tianmao2" icon-class="wysj-tianmao2"></a></li>
		<li><a href="javascript:;" class="wysj wysj-tianmao1" icon-class="wysj-tianmao1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-liaotian1" icon-class="wysj-liaotian1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-kefu2" icon-class="wysj-kefu2"></a></li>
		<li><a href="javascript:;" class="wysj wysj-ren1" icon-class="wysj-ren1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-dingbu1" icon-class="wysj-dingbu1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-jingdong2" icon-class="wysj-jingdong2"></a></li>
		<li><a href="javascript:;" class="wysj wysj-wangwang" icon-class="wysj-wangwang"></a></li>
		<li><a href="javascript:;" class="wysj wysj-83" icon-class="wysj-83"></a></li>
		<li><a href="javascript:;" class="wysj wysj-icon-" icon-class="wysj-icon-"></a></li>
		<li><a href="javascript:;" class="wysj wysj-tianmao" icon-class="wysj-tianmao"></a></li>
		<li><a href="javascript:;" class="wysj wysj-ren" icon-class="wysj-ren"></a></li>
		<li><a href="javascript:;" class="wysj wysj-dingbu" icon-class="wysj-dingbu"></a></li>
		<li><a href="javascript:;" class="wysj wysj-xiaolaba" icon-class="wysj-xiaolaba"></a></li>
		<li><a href="javascript:;" class="wysj wysj-aliww" icon-class="wysj-aliww"></a></li>
		<li><a href="javascript:;" class="wysj wysj-liaotian" icon-class="wysj-liaotian"></a></li>
		<li><a href="javascript:;" class="wysj wysj-laba" icon-class="wysj-laba"></a></li>
		<li><a href="javascript:;" class="wysj wysj-facebook1" icon-class="wysj-facebook1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-erweima1" icon-class="wysj-erweima1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-skype1" icon-class="wysj-skype1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-douban-copy" icon-class="wysj-douban-copy"></a></li>
		<li><a href="javascript:;" class="wysj wysj-tengxunweibo1" icon-class="wysj-tengxunweibo1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-weixin-copy" icon-class="wysj-weixin-copy"></a></li>
		<li><a href="javascript:;" class="wysj wysj-qqqun" icon-class="wysj-qqqun"></a></li>
		<li><a href="javascript:;" class="wysj wysj-facebookicon" icon-class="wysj-facebookicon"></a></li>
		<li><a href="javascript:;" class="wysj wysj-dianhua" icon-class="wysj-dianhua"></a></li>
		<li><a href="javascript:;" class="wysj wysj-kefu1" icon-class="wysj-kefu1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-qq1" icon-class="wysj-qq1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-taobao" icon-class="wysj-taobao"></a></li>
		<li><a href="javascript:;" class="wysj wysj-googleplus" icon-class="wysj-googleplus"></a></li>
		<li><a href="javascript:;" class="wysj wysj-facebook" icon-class="wysj-facebook"></a></li>
		<li><a href="javascript:;" class="wysj wysj-tengxunweibo" icon-class="wysj-tengxunweibo"></a></li>
		<li><a href="javascript:;" class="wysj wysj-qq" icon-class="wysj-qq"></a></li>
		<li><a href="javascript:;" class="wysj wysj-qqkongjian1" icon-class="wysj-qqkongjian1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-gouwuche1" icon-class="wysj-gouwuche1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-wangwang-b" icon-class="wysj-wangwang-b"></a></li>
		<li><a href="javascript:;" class="wysj wysj-xinlang" icon-class="wysj-xinlang"></a></li>
		<li><a href="javascript:;" class="wysj wysj-top" icon-class="wysj-top"></a></li>
		<li><a href="javascript:;" class="wysj wysj-erweima" icon-class="wysj-erweima"></a></li>
		<li><a href="javascript:;" class="wysj wysj-buchongiconsvg02" icon-class="wysj-buchongiconsvg02"></a></li>
		<li><a href="javascript:;" class="wysj wysj-gouwucheshoppingcart" icon-class="wysj-gouwucheshoppingcart"></a></li>
		<li><a href="javascript:;" class="wysj wysj-twitter1" icon-class="wysj-twitter1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-twitter" icon-class="wysj-twitter"></a></li>
		<li><a href="javascript:;" class="wysj wysj-kefu" icon-class="wysj-kefu"></a></li>
		<li><a href="javascript:;" class="wysj wysj-google26" icon-class="wysj-google26"></a></li>
		<li><a href="javascript:;" class="wysj wysj-tengxunpengyou" icon-class="wysj-tengxunpengyou"></a></li>
		<li><a href="javascript:;" class="wysj wysj-qqkongjian" icon-class="wysj-qqkongjian"></a></li>
		<li><a href="javascript:;" class="wysj wysj-liaotian2" icon-class="wysj-liaotian2"></a></li>
		<li><a href="javascript:;" class="wysj wysj-iconfontcolor39" icon-class="wysj-iconfontcolor39"></a></li>
		<li><a href="javascript:;" class="wysj wysj-googleplussquare" icon-class="wysj-googleplussquare"></a></li>
		<li><a href="javascript:;" class="wysj wysj-skype" icon-class="wysj-skype"></a></li>
		<li><a href="javascript:;" class="wysj wysj-douban" icon-class="wysj-douban"></a></li>
		<li><a href="javascript:;" class="wysj wysj-gouwuche" icon-class="wysj-gouwuche"></a></li>
		<li><a href="javascript:;" class="wysj wysj-bags" icon-class="wysj-bags"></a></li>
		<li><a href="javascript:;" class="wysj wysj-apparel" icon-class="wysj-apparel"></a></li>
		<li><a href="javascript:;" class="wysj wysj-password" icon-class="wysj-password"></a></li>
		<li><a href="javascript:;" class="wysj wysj-trust" icon-class="wysj-trust"></a></li>
		<li><a href="javascript:;" class="wysj wysj-task-management" icon-class="wysj-task-management"></a></li>
		<li><a href="javascript:;" class="wysj wysj-earth" icon-class="wysj-earth"></a></li>
		<li><a href="javascript:;" class="wysj wysj-video" icon-class="wysj-video"></a></li>
		<li><a href="javascript:;" class="wysj wysj-Calculator" icon-class="wysj-Calculator"></a></li>
		<li><a href="javascript:;" class="wysj wysj-originalimage" icon-class="wysj-originalimage"></a></li>
		<li><a href="javascript:;" class="wysj wysj-pic-filling" icon-class="wysj-pic-filling"></a></li>
		<li><a href="javascript:;" class="wysj wysj-favorites" icon-class="wysj-favorites"></a></li>
		<li><a href="javascript:;" class="wysj wysj-browse1" icon-class="wysj-browse1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-trade" icon-class="wysj-trade"></a></li>
		<li><a href="javascript:;" class="wysj wysj-ship" icon-class="wysj-ship"></a></li>
		<li><a href="javascript:;" class="wysj wysj-yuyin" icon-class="wysj-yuyin"></a></li>
		<li><a href="javascript:;" class="wysj wysj-mian" icon-class="wysj-mian"></a></li>
		<li><a href="javascript:;" class="wysj wysj-7" icon-class="wysj-7"></a></li>
		<li><a href="javascript:;" class="wysj wysj-zhiliangbz" icon-class="wysj-zhiliangbz"></a></li>
		<li><a href="javascript:;" class="wysj wysj-zhifubaofukuan" icon-class="wysj-zhifubaofukuan"></a></li>
		<li><a href="javascript:;" class="wysj wysj-zhengpinbz" icon-class="wysj-zhengpinbz"></a></li>
		<li><a href="javascript:;" class="wysj wysj-suyuanzhijianbz" icon-class="wysj-suyuanzhijianbz"></a></li>
		<li><a href="javascript:;" class="wysj wysj-shenduyanshang" icon-class="wysj-shenduyanshang"></a></li>
		<li><a href="javascript:;" class="wysj wysj-shendurz" icon-class="wysj-shendurz"></a></li>
		<li><a href="javascript:;" class="wysj wysj-posunbuji" icon-class="wysj-posunbuji"></a></li>
		<li><a href="javascript:;" class="wysj wysj-maijiabz" icon-class="wysj-maijiabz"></a></li>
		<li><a href="javascript:;" class="wysj wysj-jisukuikuan" icon-class="wysj-jisukuikuan"></a></li>
		<li><a href="javascript:;" class="wysj wysj-jinpaigongyings" icon-class="wysj-jinpaigongyings"></a></li>
		<li><a href="javascript:;" class="wysj wysj-jingpaicaigoushang" icon-class="wysj-jingpaicaigoushang"></a></li>
		<li><a href="javascript:;" class="wysj wysj-jiaoqibz" icon-class="wysj-jiaoqibz"></a></li>
		<li><a href="javascript:;" class="wysj wysj-save" icon-class="wysj-save"></a></li>
		<li><a href="javascript:;" class="wysj wysj-copy" icon-class="wysj-copy"></a></li>
		<li><a href="javascript:;" class="wysj wysj-huo" icon-class="wysj-huo"></a></li>
		<li><a href="javascript:;" class="wysj wysj-ju1" icon-class="wysj-ju1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-hua" icon-class="wysj-hua"></a></li>
		<li><a href="javascript:;" class="wysj wysj-suan" icon-class="wysj-suan"></a></li>
		<li><a href="javascript:;" class="wysj wysj-ju" icon-class="wysj-ju"></a></li>
		<li><a href="javascript:;" class="wysj wysj-accountfilling" icon-class="wysj-accountfilling"></a></li>
		<li><a href="javascript:;" class="wysj wysj-favoritesfilling" icon-class="wysj-favoritesfilling"></a></li>
		<li><a href="javascript:;" class="wysj wysj-mobilephone" icon-class="wysj-mobilephone"></a></li>
		<li><a href="javascript:;" class="wysj wysj-shoes" icon-class="wysj-shoes"></a></li>
		<li><a href="javascript:;" class="wysj wysj-phone" icon-class="wysj-phone"></a></li>
		<li><a href="javascript:;" class="wysj wysj-share" icon-class="wysj-share"></a></li>
		<li><a href="javascript:;" class="wysj wysj-security" icon-class="wysj-security"></a></li>
		<li><a href="javascript:;" class="wysj wysj-compass" icon-class="wysj-compass"></a></li>
		<li><a href="javascript:;" class="wysj wysj-iconfontstop" icon-class="wysj-iconfontstop"></a></li>
		<li><a href="javascript:;" class="wysj wysj-iconfontplay2" icon-class="wysj-iconfontplay2"></a></li>
		<li><a href="javascript:;" class="wysj wysj-skip" icon-class="wysj-skip"></a></li>
		<li><a href="javascript:;" class="wysj wysj-good" icon-class="wysj-good"></a></li>
		<li><a href="javascript:;" class="wysj wysj-bad" icon-class="wysj-bad"></a></li>
		<li><a href="javascript:;" class="wysj wysj-map" icon-class="wysj-map"></a></li>
		<li><a href="javascript:;" class="wysj wysj-icondownload" icon-class="wysj-icondownload"></a></li>
		<li><a href="javascript:;" class="wysj wysj-remind" icon-class="wysj-remind"></a></li>
		<li><a href="javascript:;" class="wysj wysj-jifen" icon-class="wysj-jifen"></a></li>
		<li><a href="javascript:;" class="wysj wysj-office" icon-class="wysj-office"></a></li>
		<li><a href="javascript:;" class="wysj wysj-dollar" icon-class="wysj-dollar"></a></li>
		<li><a href="javascript:;" class="wysj wysj-move" icon-class="wysj-move"></a></li>
		<li><a href="javascript:;" class="wysj wysj-text" icon-class="wysj-text"></a></li>
		<li><a href="javascript:;" class="wysj wysj-navlist" icon-class="wysj-navlist"></a></li>
		<li><a href="javascript:;" class="wysj wysj-link" icon-class="wysj-link"></a></li>
		<li><a href="javascript:;" class="wysj wysj-history" icon-class="wysj-history"></a></li>
		<li><a href="javascript:;" class="wysj wysj-pin" icon-class="wysj-pin"></a></li>
		<li><a href="javascript:;" class="wysj wysj-filter" icon-class="wysj-filter"></a></li>
		<li><a href="javascript:;" class="wysj wysj-scanning" icon-class="wysj-scanning"></a></li>
		<li><a href="javascript:;" class="wysj wysj-rfq" icon-class="wysj-rfq"></a></li>
		<li><a href="javascript:;" class="wysj wysj-atmaway" icon-class="wysj-atmaway"></a></li>
		<li><a href="javascript:;" class="wysj wysj-rfqqm" icon-class="wysj-rfqqm"></a></li>
		<li><a href="javascript:;" class="wysj wysj-browse" icon-class="wysj-browse"></a></li>
		<li><a href="javascript:;" class="wysj wysj-jewelry" icon-class="wysj-jewelry"></a></li>
		<li><a href="javascript:;" class="wysj wysj-auto" icon-class="wysj-auto"></a></li>
		<li><a href="javascript:;" class="wysj wysj-lights" icon-class="wysj-lights"></a></li>
		<li><a href="javascript:;" class="wysj wysj-gifts" icon-class="wysj-gifts"></a></li>
		<li><a href="javascript:;" class="wysj wysj-electronics" icon-class="wysj-electronics"></a></li>
		<li><a href="javascript:;" class="wysj wysj-electrical" icon-class="wysj-electrical"></a></li>
		<li><a href="javascript:;" class="wysj wysj-process" icon-class="wysj-process"></a></li>
		<li><a href="javascript:;" class="wysj wysj-print" icon-class="wysj-print"></a></li>
		<li><a href="javascript:;" class="wysj wysj-service" icon-class="wysj-service"></a></li>
		<li><a href="javascript:;" class="wysj wysj-discount" icon-class="wysj-discount"></a></li>
		<li><a href="javascript:;" class="wysj wysj-attachment" icon-class="wysj-attachment"></a></li>
		<li><a href="javascript:;" class="wysj wysj-calendar" icon-class="wysj-calendar"></a></li>
		<li><a href="javascript:;" class="wysj wysj-clock" icon-class="wysj-clock"></a></li>
		<li><a href="javascript:;" class="wysj wysj-atm" icon-class="wysj-atm"></a></li>
		<li><a href="javascript:;" class="wysj wysj-add" icon-class="wysj-add"></a></li>
		<li><a href="javascript:;" class="wysj wysj-account" icon-class="wysj-account"></a></li>
		<li><a href="javascript:;" class="wysj wysj-wrong" icon-class="wysj-wrong"></a></li>
		<li><a href="javascript:;" class="wysj wysj-warning" icon-class="wysj-warning"></a></li>
		<li><a href="javascript:;" class="wysj wysj-viewlist" icon-class="wysj-viewlist"></a></li>
		<li><a href="javascript:;" class="wysj wysj-viewgallery" icon-class="wysj-viewgallery"></a></li>
		<li><a href="javascript:;" class="wysj wysj-success" icon-class="wysj-success"></a></li>
		<li><a href="javascript:;" class="wysj wysj-smile" icon-class="wysj-smile"></a></li>
		<li><a href="javascript:;" class="wysj wysj-set" icon-class="wysj-set"></a></li>
		<li><a href="javascript:;" class="wysj wysj-selected" icon-class="wysj-selected"></a></li>
		<li><a href="javascript:;" class="wysj wysj-search" icon-class="wysj-search"></a></li>
		<li><a href="javascript:;" class="wysj wysj-refresh" icon-class="wysj-refresh"></a></li>
		<li><a href="javascript:;" class="wysj wysj-qrcode" icon-class="wysj-qrcode"></a></li>
		<li><a href="javascript:;" class="wysj wysj-pic" icon-class="wysj-pic"></a></li>
		<li><a href="javascript:;" class="wysj wysj-more" icon-class="wysj-more"></a></li>
		<li><a href="javascript:;" class="wysj wysj-moreunfold" icon-class="wysj-moreunfold"></a></li>
		<li><a href="javascript:;" class="wysj wysj-information" icon-class="wysj-information"></a></li>
		<li><a href="javascript:;" class="wysj wysj-help" icon-class="wysj-help"></a></li>
		<li><a href="javascript:;" class="wysj wysj-form" icon-class="wysj-form"></a></li>
		<li><a href="javascript:;" class="wysj wysj-favorite" icon-class="wysj-favorite"></a></li>
		<li><a href="javascript:;" class="wysj wysj-email" icon-class="wysj-email"></a></li>
		<li><a href="javascript:;" class="wysj wysj-edit" icon-class="wysj-edit"></a></li>
		<li><a href="javascript:;" class="wysj wysj-delete" icon-class="wysj-delete"></a></li>
		<li><a href="javascript:;" class="wysj wysj-cry" icon-class="wysj-cry"></a></li>
		<li><a href="javascript:;" class="wysj wysj-comments" icon-class="wysj-comments"></a></li>
		<li><a href="javascript:;" class="wysj wysj-close" icon-class="wysj-close"></a></li>
		<li><a href="javascript:;" class="wysj wysj-category" icon-class="wysj-category"></a></li>
		<li><a href="javascript:;" class="wysj wysj-cart" icon-class="wysj-cart"></a></li>
		<li><a href="javascript:;" class="wysj wysj-back" icon-class="wysj-back"></a></li>
		<li><a href="javascript:;" class="wysj wysj-all" icon-class="wysj-all"></a></li>
		<li><a href="javascript:;" class="wysj wysj-email-filling" icon-class="wysj-email-filling"></a></li>
		<li><a href="javascript:;" class="wysj wysj-email5" icon-class="wysj-email5"></a></li>
		<li><a href="javascript:;" class="wysj wysj-email4" icon-class="wysj-email4"></a></li>
		<li><a href="javascript:;" class="wysj wysj-email3" icon-class="wysj-email3"></a></li>
		<li><a href="javascript:;" class="wysj wysj-email2" icon-class="wysj-email2"></a></li>
		<li><a href="javascript:;" class="wysj wysj-email1" icon-class="wysj-email1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-xiaolian4" icon-class="wysj-xiaolian4"></a></li>
		<li><a href="javascript:;" class="wysj wysj-xiaolian3" icon-class="wysj-xiaolian3"></a></li>
		<li><a href="javascript:;" class="wysj wysj-xiaolian2" icon-class="wysj-xiaolian2"></a></li>
		<li><a href="javascript:;" class="wysj wysj-xiaolian1" icon-class="wysj-xiaolian1"></a></li>
		<li><a href="javascript:;" class="wysj wysj-xiaolian" icon-class="wysj-xiaolian"></a></li>
	</ul>
</div>
<script type="text/javascript">
	jQuery(function() {
		var theA = jQuery('#<?php echo $boxId; ?>').find('a');
		theA.on('click', function(event) {
			if(confirm('升级到完整版开启自定义图标功能，马上获取完整版？')){
				location.href = 'https://www.5usj.cn/wp/5usujian-super-serv/'
			}
		});
	});
</script>
<?php
}
?>
<?php
function wysj_serv_choseiconbox($boxId)//自定义图标选择
{
?>
<div id="wy-chose-box" class="wy-chose-box">
	<a href="javaScript:;" class="wysj wysj-close wy-close-chose" onclick="wysjAdmin.closeChose()"></a>
	<div class="wy-iconbox" id="<?php echo $boxId; ?>">
		<ul>
			<li><a href="javascript:;" class="wysj wysj-whatsapp1" icon-class="wysj-whatsapp1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-whatsApp" icon-class="wysj-whatsApp"></a></li>
			<li><a href="javascript:;" class="wysj wysj-whatsapp" icon-class="wysj-whatsapp"></a></li>
			<li><a href="javascript:;" class="wysj wysj-huanyihuan" icon-class="wysj-huanyihuan"></a></li>
			<li><a href="javascript:;" class="wysj wysj-changyonggoupiaorenshanchu" icon-class="wysj-changyonggoupiaorenshanchu"></a></li>
			<li><a href="javascript:;" class="wysj wysj-yanchurili" icon-class="wysj-yanchurili"></a></li>
			<li><a href="javascript:;" class="wysj wysj-qiandao" icon-class="wysj-qiandao"></a></li>
			<li><a href="javascript:;" class="wysj wysj-xiaoxi" icon-class="wysj-xiaoxi"></a></li>
			<li><a href="javascript:;" class="wysj wysj-saoyisao1" icon-class="wysj-saoyisao1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-shoucang" icon-class="wysj-shoucang"></a></li>
			<li><a href="javascript:;" class="wysj wysj-zanting" icon-class="wysj-zanting"></a></li>
			<li><a href="javascript:;" class="wysj wysj-shenfenzheng" icon-class="wysj-shenfenzheng"></a></li>
			<li><a href="javascript:;" class="wysj wysj-bofang" icon-class="wysj-bofang"></a></li>
			<li><a href="javascript:;" class="wysj wysj-saoyisao" icon-class="wysj-saoyisao"></a></li>
			<li><a href="javascript:;" class="wysj wysj-qqqun1" icon-class="wysj-qqqun1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-tieba" icon-class="wysj-tieba"></a></li>
			<li><a href="javascript:;" class="wysj wysj-tianmao3" icon-class="wysj-tianmao3"></a></li>
			<li><a href="javascript:;" class="wysj wysj-tianmao2" icon-class="wysj-tianmao2"></a></li>
			<li><a href="javascript:;" class="wysj wysj-tianmao1" icon-class="wysj-tianmao1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-liaotian1" icon-class="wysj-liaotian1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-kefu2" icon-class="wysj-kefu2"></a></li>
			<li><a href="javascript:;" class="wysj wysj-ren1" icon-class="wysj-ren1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-dingbu1" icon-class="wysj-dingbu1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-jingdong2" icon-class="wysj-jingdong2"></a></li>
			<li><a href="javascript:;" class="wysj wysj-wangwang" icon-class="wysj-wangwang"></a></li>
			<li><a href="javascript:;" class="wysj wysj-83" icon-class="wysj-83"></a></li>
			<li><a href="javascript:;" class="wysj wysj-icon-" icon-class="wysj-icon-"></a></li>
			<li><a href="javascript:;" class="wysj wysj-tianmao" icon-class="wysj-tianmao"></a></li>
			<li><a href="javascript:;" class="wysj wysj-ren" icon-class="wysj-ren"></a></li>
			<li><a href="javascript:;" class="wysj wysj-dingbu" icon-class="wysj-dingbu"></a></li>
			<li><a href="javascript:;" class="wysj wysj-xiaolaba" icon-class="wysj-xiaolaba"></a></li>
			<li><a href="javascript:;" class="wysj wysj-aliww" icon-class="wysj-aliww"></a></li>
			<li><a href="javascript:;" class="wysj wysj-liaotian" icon-class="wysj-liaotian"></a></li>
			<li><a href="javascript:;" class="wysj wysj-laba" icon-class="wysj-laba"></a></li>
			<li><a href="javascript:;" class="wysj wysj-facebook1" icon-class="wysj-facebook1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-erweima1" icon-class="wysj-erweima1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-skype1" icon-class="wysj-skype1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-douban-copy" icon-class="wysj-douban-copy"></a></li>
			<li><a href="javascript:;" class="wysj wysj-tengxunweibo1" icon-class="wysj-tengxunweibo1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-weixin-copy" icon-class="wysj-weixin-copy"></a></li>
			<li><a href="javascript:;" class="wysj wysj-qqqun" icon-class="wysj-qqqun"></a></li>
			<li><a href="javascript:;" class="wysj wysj-facebookicon" icon-class="wysj-facebookicon"></a></li>
			<li><a href="javascript:;" class="wysj wysj-dianhua" icon-class="wysj-dianhua"></a></li>
			<li><a href="javascript:;" class="wysj wysj-kefu1" icon-class="wysj-kefu1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-qq1" icon-class="wysj-qq1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-taobao" icon-class="wysj-taobao"></a></li>
			<li><a href="javascript:;" class="wysj wysj-googleplus" icon-class="wysj-googleplus"></a></li>
			<li><a href="javascript:;" class="wysj wysj-facebook" icon-class="wysj-facebook"></a></li>
			<li><a href="javascript:;" class="wysj wysj-tengxunweibo" icon-class="wysj-tengxunweibo"></a></li>
			<li><a href="javascript:;" class="wysj wysj-qq" icon-class="wysj-qq"></a></li>
			<li><a href="javascript:;" class="wysj wysj-qqkongjian1" icon-class="wysj-qqkongjian1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-gouwuche1" icon-class="wysj-gouwuche1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-wangwang-b" icon-class="wysj-wangwang-b"></a></li>
			<li><a href="javascript:;" class="wysj wysj-xinlang" icon-class="wysj-xinlang"></a></li>
			<li><a href="javascript:;" class="wysj wysj-top" icon-class="wysj-top"></a></li>
			<li><a href="javascript:;" class="wysj wysj-erweima" icon-class="wysj-erweima"></a></li>
			<li><a href="javascript:;" class="wysj wysj-buchongiconsvg02" icon-class="wysj-buchongiconsvg02"></a></li>
			<li><a href="javascript:;" class="wysj wysj-gouwucheshoppingcart" icon-class="wysj-gouwucheshoppingcart"></a></li>
			<li><a href="javascript:;" class="wysj wysj-twitter1" icon-class="wysj-twitter1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-twitter" icon-class="wysj-twitter"></a></li>
			<li><a href="javascript:;" class="wysj wysj-kefu" icon-class="wysj-kefu"></a></li>
			<li><a href="javascript:;" class="wysj wysj-google26" icon-class="wysj-google26"></a></li>
			<li><a href="javascript:;" class="wysj wysj-tengxunpengyou" icon-class="wysj-tengxunpengyou"></a></li>
			<li><a href="javascript:;" class="wysj wysj-qqkongjian" icon-class="wysj-qqkongjian"></a></li>
			<li><a href="javascript:;" class="wysj wysj-liaotian2" icon-class="wysj-liaotian2"></a></li>
			<li><a href="javascript:;" class="wysj wysj-iconfontcolor39" icon-class="wysj-iconfontcolor39"></a></li>
			<li><a href="javascript:;" class="wysj wysj-googleplussquare" icon-class="wysj-googleplussquare"></a></li>
			<li><a href="javascript:;" class="wysj wysj-skype" icon-class="wysj-skype"></a></li>
			<li><a href="javascript:;" class="wysj wysj-douban" icon-class="wysj-douban"></a></li>
			<li><a href="javascript:;" class="wysj wysj-gouwuche" icon-class="wysj-gouwuche"></a></li>
			<li><a href="javascript:;" class="wysj wysj-bags" icon-class="wysj-bags"></a></li>
			<li><a href="javascript:;" class="wysj wysj-apparel" icon-class="wysj-apparel"></a></li>
			<li><a href="javascript:;" class="wysj wysj-password" icon-class="wysj-password"></a></li>
			<li><a href="javascript:;" class="wysj wysj-trust" icon-class="wysj-trust"></a></li>
			<li><a href="javascript:;" class="wysj wysj-task-management" icon-class="wysj-task-management"></a></li>
			<li><a href="javascript:;" class="wysj wysj-earth" icon-class="wysj-earth"></a></li>
			<li><a href="javascript:;" class="wysj wysj-video" icon-class="wysj-video"></a></li>
			<li><a href="javascript:;" class="wysj wysj-Calculator" icon-class="wysj-Calculator"></a></li>
			<li><a href="javascript:;" class="wysj wysj-originalimage" icon-class="wysj-originalimage"></a></li>
			<li><a href="javascript:;" class="wysj wysj-pic-filling" icon-class="wysj-pic-filling"></a></li>
			<li><a href="javascript:;" class="wysj wysj-favorites" icon-class="wysj-favorites"></a></li>
			<li><a href="javascript:;" class="wysj wysj-browse1" icon-class="wysj-browse1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-trade" icon-class="wysj-trade"></a></li>
			<li><a href="javascript:;" class="wysj wysj-ship" icon-class="wysj-ship"></a></li>
			<li><a href="javascript:;" class="wysj wysj-yuyin" icon-class="wysj-yuyin"></a></li>
			<li><a href="javascript:;" class="wysj wysj-mian" icon-class="wysj-mian"></a></li>
			<li><a href="javascript:;" class="wysj wysj-7" icon-class="wysj-7"></a></li>
			<li><a href="javascript:;" class="wysj wysj-zhiliangbz" icon-class="wysj-zhiliangbz"></a></li>
			<li><a href="javascript:;" class="wysj wysj-zhifubaofukuan" icon-class="wysj-zhifubaofukuan"></a></li>
			<li><a href="javascript:;" class="wysj wysj-zhengpinbz" icon-class="wysj-zhengpinbz"></a></li>
			<li><a href="javascript:;" class="wysj wysj-suyuanzhijianbz" icon-class="wysj-suyuanzhijianbz"></a></li>
			<li><a href="javascript:;" class="wysj wysj-shenduyanshang" icon-class="wysj-shenduyanshang"></a></li>
			<li><a href="javascript:;" class="wysj wysj-shendurz" icon-class="wysj-shendurz"></a></li>
			<li><a href="javascript:;" class="wysj wysj-posunbuji" icon-class="wysj-posunbuji"></a></li>
			<li><a href="javascript:;" class="wysj wysj-maijiabz" icon-class="wysj-maijiabz"></a></li>
			<li><a href="javascript:;" class="wysj wysj-jisukuikuan" icon-class="wysj-jisukuikuan"></a></li>
			<li><a href="javascript:;" class="wysj wysj-jinpaigongyings" icon-class="wysj-jinpaigongyings"></a></li>
			<li><a href="javascript:;" class="wysj wysj-jingpaicaigoushang" icon-class="wysj-jingpaicaigoushang"></a></li>
			<li><a href="javascript:;" class="wysj wysj-jiaoqibz" icon-class="wysj-jiaoqibz"></a></li>
			<li><a href="javascript:;" class="wysj wysj-save" icon-class="wysj-save"></a></li>
			<li><a href="javascript:;" class="wysj wysj-copy" icon-class="wysj-copy"></a></li>
			<li><a href="javascript:;" class="wysj wysj-huo" icon-class="wysj-huo"></a></li>
			<li><a href="javascript:;" class="wysj wysj-ju1" icon-class="wysj-ju1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-hua" icon-class="wysj-hua"></a></li>
			<li><a href="javascript:;" class="wysj wysj-suan" icon-class="wysj-suan"></a></li>
			<li><a href="javascript:;" class="wysj wysj-ju" icon-class="wysj-ju"></a></li>
			<li><a href="javascript:;" class="wysj wysj-accountfilling" icon-class="wysj-accountfilling"></a></li>
			<li><a href="javascript:;" class="wysj wysj-favoritesfilling" icon-class="wysj-favoritesfilling"></a></li>
			<li><a href="javascript:;" class="wysj wysj-mobilephone" icon-class="wysj-mobilephone"></a></li>
			<li><a href="javascript:;" class="wysj wysj-shoes" icon-class="wysj-shoes"></a></li>
			<li><a href="javascript:;" class="wysj wysj-phone" icon-class="wysj-phone"></a></li>
			<li><a href="javascript:;" class="wysj wysj-share" icon-class="wysj-share"></a></li>
			<li><a href="javascript:;" class="wysj wysj-security" icon-class="wysj-security"></a></li>
			<li><a href="javascript:;" class="wysj wysj-compass" icon-class="wysj-compass"></a></li>
			<li><a href="javascript:;" class="wysj wysj-iconfontstop" icon-class="wysj-iconfontstop"></a></li>
			<li><a href="javascript:;" class="wysj wysj-iconfontplay2" icon-class="wysj-iconfontplay2"></a></li>
			<li><a href="javascript:;" class="wysj wysj-skip" icon-class="wysj-skip"></a></li>
			<li><a href="javascript:;" class="wysj wysj-good" icon-class="wysj-good"></a></li>
			<li><a href="javascript:;" class="wysj wysj-bad" icon-class="wysj-bad"></a></li>
			<li><a href="javascript:;" class="wysj wysj-map" icon-class="wysj-map"></a></li>
			<li><a href="javascript:;" class="wysj wysj-icondownload" icon-class="wysj-icondownload"></a></li>
			<li><a href="javascript:;" class="wysj wysj-remind" icon-class="wysj-remind"></a></li>
			<li><a href="javascript:;" class="wysj wysj-jifen" icon-class="wysj-jifen"></a></li>
			<li><a href="javascript:;" class="wysj wysj-office" icon-class="wysj-office"></a></li>
			<li><a href="javascript:;" class="wysj wysj-dollar" icon-class="wysj-dollar"></a></li>
			<li><a href="javascript:;" class="wysj wysj-move" icon-class="wysj-move"></a></li>
			<li><a href="javascript:;" class="wysj wysj-text" icon-class="wysj-text"></a></li>
			<li><a href="javascript:;" class="wysj wysj-navlist" icon-class="wysj-navlist"></a></li>
			<li><a href="javascript:;" class="wysj wysj-link" icon-class="wysj-link"></a></li>
			<li><a href="javascript:;" class="wysj wysj-history" icon-class="wysj-history"></a></li>
			<li><a href="javascript:;" class="wysj wysj-pin" icon-class="wysj-pin"></a></li>
			<li><a href="javascript:;" class="wysj wysj-filter" icon-class="wysj-filter"></a></li>
			<li><a href="javascript:;" class="wysj wysj-scanning" icon-class="wysj-scanning"></a></li>
			<li><a href="javascript:;" class="wysj wysj-rfq" icon-class="wysj-rfq"></a></li>
			<li><a href="javascript:;" class="wysj wysj-atmaway" icon-class="wysj-atmaway"></a></li>
			<li><a href="javascript:;" class="wysj wysj-rfqqm" icon-class="wysj-rfqqm"></a></li>
			<li><a href="javascript:;" class="wysj wysj-browse" icon-class="wysj-browse"></a></li>
			<li><a href="javascript:;" class="wysj wysj-jewelry" icon-class="wysj-jewelry"></a></li>
			<li><a href="javascript:;" class="wysj wysj-auto" icon-class="wysj-auto"></a></li>
			<li><a href="javascript:;" class="wysj wysj-lights" icon-class="wysj-lights"></a></li>
			<li><a href="javascript:;" class="wysj wysj-gifts" icon-class="wysj-gifts"></a></li>
			<li><a href="javascript:;" class="wysj wysj-electronics" icon-class="wysj-electronics"></a></li>
			<li><a href="javascript:;" class="wysj wysj-electrical" icon-class="wysj-electrical"></a></li>
			<li><a href="javascript:;" class="wysj wysj-process" icon-class="wysj-process"></a></li>
			<li><a href="javascript:;" class="wysj wysj-print" icon-class="wysj-print"></a></li>
			<li><a href="javascript:;" class="wysj wysj-service" icon-class="wysj-service"></a></li>
			<li><a href="javascript:;" class="wysj wysj-discount" icon-class="wysj-discount"></a></li>
			<li><a href="javascript:;" class="wysj wysj-attachment" icon-class="wysj-attachment"></a></li>
			<li><a href="javascript:;" class="wysj wysj-calendar" icon-class="wysj-calendar"></a></li>
			<li><a href="javascript:;" class="wysj wysj-clock" icon-class="wysj-clock"></a></li>
			<li><a href="javascript:;" class="wysj wysj-atm" icon-class="wysj-atm"></a></li>
			<li><a href="javascript:;" class="wysj wysj-add" icon-class="wysj-add"></a></li>
			<li><a href="javascript:;" class="wysj wysj-account" icon-class="wysj-account"></a></li>
			<li><a href="javascript:;" class="wysj wysj-wrong" icon-class="wysj-wrong"></a></li>
			<li><a href="javascript:;" class="wysj wysj-warning" icon-class="wysj-warning"></a></li>
			<li><a href="javascript:;" class="wysj wysj-viewlist" icon-class="wysj-viewlist"></a></li>
			<li><a href="javascript:;" class="wysj wysj-viewgallery" icon-class="wysj-viewgallery"></a></li>
			<li><a href="javascript:;" class="wysj wysj-success" icon-class="wysj-success"></a></li>
			<li><a href="javascript:;" class="wysj wysj-smile" icon-class="wysj-smile"></a></li>
			<li><a href="javascript:;" class="wysj wysj-set" icon-class="wysj-set"></a></li>
			<li><a href="javascript:;" class="wysj wysj-selected" icon-class="wysj-selected"></a></li>
			<li><a href="javascript:;" class="wysj wysj-search" icon-class="wysj-search"></a></li>
			<li><a href="javascript:;" class="wysj wysj-refresh" icon-class="wysj-refresh"></a></li>
			<li><a href="javascript:;" class="wysj wysj-qrcode" icon-class="wysj-qrcode"></a></li>
			<li><a href="javascript:;" class="wysj wysj-pic" icon-class="wysj-pic"></a></li>
			<li><a href="javascript:;" class="wysj wysj-more" icon-class="wysj-more"></a></li>
			<li><a href="javascript:;" class="wysj wysj-moreunfold" icon-class="wysj-moreunfold"></a></li>
			<li><a href="javascript:;" class="wysj wysj-information" icon-class="wysj-information"></a></li>
			<li><a href="javascript:;" class="wysj wysj-help" icon-class="wysj-help"></a></li>
			<li><a href="javascript:;" class="wysj wysj-form" icon-class="wysj-form"></a></li>
			<li><a href="javascript:;" class="wysj wysj-favorite" icon-class="wysj-favorite"></a></li>
			<li><a href="javascript:;" class="wysj wysj-email" icon-class="wysj-email"></a></li>
			<li><a href="javascript:;" class="wysj wysj-edit" icon-class="wysj-edit"></a></li>
			<li><a href="javascript:;" class="wysj wysj-delete" icon-class="wysj-delete"></a></li>
			<li><a href="javascript:;" class="wysj wysj-cry" icon-class="wysj-cry"></a></li>
			<li><a href="javascript:;" class="wysj wysj-comments" icon-class="wysj-comments"></a></li>
			<li><a href="javascript:;" class="wysj wysj-close" icon-class="wysj-close"></a></li>
			<li><a href="javascript:;" class="wysj wysj-category" icon-class="wysj-category"></a></li>
			<li><a href="javascript:;" class="wysj wysj-cart" icon-class="wysj-cart"></a></li>
			<li><a href="javascript:;" class="wysj wysj-back" icon-class="wysj-back"></a></li>
			<li><a href="javascript:;" class="wysj wysj-all" icon-class="wysj-all"></a></li>
			<li><a href="javascript:;" class="wysj wysj-email-filling" icon-class="wysj-email-filling"></a></li>
			<li><a href="javascript:;" class="wysj wysj-email5" icon-class="wysj-email5"></a></li>
			<li><a href="javascript:;" class="wysj wysj-email4" icon-class="wysj-email4"></a></li>
			<li><a href="javascript:;" class="wysj wysj-email3" icon-class="wysj-email3"></a></li>
			<li><a href="javascript:;" class="wysj wysj-email2" icon-class="wysj-email2"></a></li>
			<li><a href="javascript:;" class="wysj wysj-email1" icon-class="wysj-email1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-xiaolian4" icon-class="wysj-xiaolian4"></a></li>
			<li><a href="javascript:;" class="wysj wysj-xiaolian3" icon-class="wysj-xiaolian3"></a></li>
			<li><a href="javascript:;" class="wysj wysj-xiaolian2" icon-class="wysj-xiaolian2"></a></li>
			<li><a href="javascript:;" class="wysj wysj-xiaolian1" icon-class="wysj-xiaolian1"></a></li>
			<li><a href="javascript:;" class="wysj wysj-xiaolian" icon-class="wysj-xiaolian"></a></li>
		</ul>
	</div>
</div>
<?php
}
?>
